export const CONNECT_TO_SOCKET = "CONNECT_TO_SOCKET"
export const CONNECT_TO_SOCKET_OK = CONNECT_TO_SOCKET + "_OK"
export const CONNECT_TO_SOCKET_ERROR = CONNECT_TO_SOCKET + "_ERROR"

export const JOIN_CHANNEL = "JOIN_CHANNEL"
export const JOIN_CHANNEL_OK = "JOIN_CHANNEL_OK"
export const JOIN_CHANNEL_ERROR = "JOIN_CHANNEL_ERROR"

export const LEAVE_CHANNEL = "LEAVE_CHANNEL"
export const LEAVE_CHANNEL_OK = "LEAVE_CHANNEL_OK"
export const LEAVE_CHANNEL_ERROR = "LEAVE_CHANNEL_ERROR"

export const EVENT_RECEIVED = "EVENT_RECEIVED"

export const EVENT_PUSH = "EVENT_PUSH"
export const EVENT_PUSH_OK = "EVENT_PUSH_OK"
export const EVENT_PUSH_ERROR = "EVENT_PUSH_ERROR"

const GET_MESSAGES = "GET_MESSAGES"
const GET_MESSAGES_OK = "GET_MESSAGES_OK"
const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR"

const CREATE_CHAT_WITH_BUSINESS = "CREATE_CHAT_WITH_BUSINESS"

const CREATE_BROADCAST = "CREATE_BROADCAST"
