// flow-typed signature: 1b0d8aae04c2eff66d075b2a1f53d8a3
// flow-typed version: <<STUB>>/phoenix_v^1.3.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phoenix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'phoenix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phoenix/assets/js/phoenix' {
  declare module.exports: any;
}

declare module 'phoenix/priv/static/phoenix' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phoenix/assets/js/phoenix.js' {
  declare module.exports: $Exports<'phoenix/assets/js/phoenix'>;
}
declare module 'phoenix/priv/static/phoenix.js' {
  declare module.exports: $Exports<'phoenix/priv/static/phoenix'>;
}
